
export const metadata = {
  title: "Next.js Pay.jp Checkout Sample App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}){
  return (
    <html lang="ja">
      <head />
      <body>
        {children}
      </body>
    </html>
  )
}